### ISSUE TITLE
About the vscode environment

### ISSUE THREAD

**Issue by lux10n** [jjdavy225/agence_voyage_java#1]
I'd like to know, how is your environment set up ?
And the dependencies to install ?
How do I get my computer ready ?
Send help I'm lost

**Comment by jjdavy225** [comment]
Just install the JAVA extension on vscode.

And you will also need a JAVA dev kit.
After that, it'll be okay i hope.

**Comment by lux10n** [comment]
kk, imma watch the repo, waiting for some further updates.

**Comment by jjdavy225** [comment]
Alright

**Comment by lucgmensah** [comment]
Lol. You're very tchaipoo guy

**Comment by jjdavy225** [comment]
Lol.
